[remoting linux host] Add dpkg trigger to linux installer.
This adds some triggers to the chrome-remote-desktop package, so that
the host process is restarted whenever PAM is upgraded on the system.

(cherry picked from commit 5af190ac4f5e9743c9ecba5e945af2fdad5f38fe)

Bug: 1174251
Change-Id: I784f0b0455d9c2fbdf1bb1a5f08f1799c8feb1df
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2674160
Auto-Submit: Lambros Lambrou <lambroslambrou@chromium.org>
Commit-Queue: Jamie Walch <jamiewalch@chromium.org>
Reviewed-by: Jamie Walch <jamiewalch@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#850330}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2677725
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/branch-heads/4389@{#689}
Cr-Branched-From: 9251c5db2b6d5a59fe4eac7aafa5fed37c139bb7-refs/heads/master@{#843830}

diff --git a/remoting/host/installer/linux/debian/postinst b/remoting/host/installer/linux/debian/postinst
--- a/remoting/host/installer/linux/debian/postinst
+++ b/remoting/host/installer/linux/debian/postinst
@@ -23,6 +23,15 @@ USER_SESSION_PATH="$INSTALL_DIR/user-session"
 HOST_PATH="$INSTALL_DIR/chrome-remote-desktop-host"
 CRD_GROUP="chrome-remote-desktop"
 
+restart_hosts() {
+  # Kill host processes. SIGKILL is used because the wrapper script will
+  # restart the host immediately (so any cleanup that might otherwise happen
+  # is not useful), and this ensures that hosts restart even if they are
+  # deadlocked.
+  echo "Shutting down Chrome Remote Desktop hosts (they will restart automatically)..."
+  pkill -KILL -f "^$HOST_PATH" || true
+}
+
 case "$1" in
   "configure")
     # Create CRD group if it doesn't already exist
@@ -37,12 +46,9 @@ case "$1" in
       chown root:"$CRD_GROUP" "$USER_SESSION_PATH"
       chmod u=srwx,g=rx,o=r "$USER_SESSION_PATH"
     fi
-    # Kill host processes. SIGKILL is used because the wrapper script will
-    # restart the host immediately (so any cleanup that might otherwise happen
-    # is not useful), and this ensures that hosts restart even if they are
-    # deadlocked.
-    echo "Shutting down Chrome Remote Desktop hosts (they will restart automatically)..."
-    pkill -KILL -f "^$HOST_PATH" || true
+
+    restart_hosts
+
     # If any files have changed that require the user to restart their virtual
     # desktops (eg, the wrapper script itself) then notify them but don't do
     # anything that would result in them losing state.
@@ -56,6 +62,11 @@ case "$1" in
       rm "$HASHES_FILE"
       rmdir --ignore-fail-on-non-empty "$VAR_DIR"
     fi
+    ;;
+
+  "triggered")
+    echo "Responding to dpkg trigger."
+    restart_hosts
     ;;
 esac
 
