[crd host] Kill NMHs after host updates
This allows the browser to reload the NMHs. Stale NMHs are problematic
since the mojo protocol could become incompatible with the one that the
host supports.

Rather than listing all NMH processes in the script, I just updated the
pkill pattern to kill all processes with the path starting with the
install dir. We can't kill the service script process, since it would
also kill the desktop session, and systemd wouldn't restart the service.
Conveniently, the script's path starts with /usr/bin/python3, so the
pkill pattern won't kill it.

Bug: 425464870
Change-Id: Iccdeb8bdf7ba3d4e6654c60f7c88436214aff148
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6653867
Auto-Submit: Yuwei Huang <yuweih@chromium.org>
Reviewed-by: Joe Downing <joedow@chromium.org>
Commit-Queue: Yuwei Huang <yuweih@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1476865}

diff --git a/remoting/host/installer/linux/debian/postinst b/remoting/host/installer/linux/debian/postinst
--- a/remoting/host/installer/linux/debian/postinst
+++ b/remoting/host/installer/linux/debian/postinst
@@ -23,13 +23,16 @@ USER_SESSION_PATH="$INSTALL_DIR/user-session"
 HOST_PATH="$INSTALL_DIR/chrome-remote-desktop-host"
 CRD_GROUP="chrome-remote-desktop"
 
-restart_hosts() {
-  # Kill host processes. SIGKILL is used because the wrapper script will
-  # restart the host immediately (so any cleanup that might otherwise happen
-  # is not useful), and this ensures that hosts restart even if they are
-  # deadlocked.
-  echo "Restarting Chrome Remote Desktop hosts (sessions will be unaffected)..."
-  pkill -KILL -f "^$HOST_PATH" || true
+kill_processes() {
+  # Kill CRD processes except for the service script process. The script process
+  # command line conveniently starts with /usr/bin/python3, so the pkill pattern
+  # won't kill it. SIGKILL is used because the wrapper script will restart the
+  # host immediately (so any cleanup that might otherwise happen is not useful),
+  # and this ensures that hosts restart even if they are deadlocked.
+  # TODO: yuweih - see if it's possible to restart the service script process
+  # without resetting the session.
+  echo "Killing Chrome Remote Desktop processes so that they can be reloaded (sessions will be unaffected)..."
+  pkill -KILL -f "^$INSTALL_DIR" || true
 }
 
 case "$1" in
@@ -98,7 +101,7 @@ case "$1" in
       fi
     fi
 
-    restart_hosts
+    kill_processes
 
     # If any files have changed that require the user to restart their virtual
     # desktops (eg, the wrapper script itself) then notify them but don't do
@@ -117,7 +120,7 @@ case "$1" in
 
   "triggered")
     echo "Responding to dpkg trigger."
-    restart_hosts
+    kill_processes
     ;;
 esac
 
