Migrate third_party/node_modules.tar.gz to GCS first class deps.
This migrates the webui_node_modules hooks to first class GCS
dependencies. See
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/docs/gcs_dependencies.md for more info.
There are changes made in update_npm_deps to upload
nodes_modules.tar.gz and update the DEPS automatically when the
`--upload` flag is used.

src/DEPS update is refactored out of `update_node_binaries` so it can
be reused.

The current archive, `node_modules.tar.gz`, structure has changed
because of this CL. It originally has node_modules as the top level
directory, so the archive is downloaded to `src/third_party/node` and
is extracted to `src/third_party/node/node_modules`.
In order to migrate to GCS first class, `node_modules.tar.gz` needs to
be downloaded to a clean directory. So `node_modules.tar.gz` is
repacked containing only the contents under `node_modules`, excluding
top directory. It will be downloaded to
`src/third_party/node/node_modules`and will be extracted there.
This preserves the structure when extracting the archive file and
minimize the impact of the migration.

Bug: 337332463
Change-Id: Id4f228c8297ef5f12bed1ea9be46887c1df69db4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5564966
Commit-Queue: Clifford Cheng <cliffordcheng@chromium.org>
Reviewed-by: Josip Sokcevic <sokcevic@chromium.org>
Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1313611}

diff --git a/third_party/node/update_npm_deps b/third_party/node/update_npm_deps
--- a/third_party/node/update_npm_deps
+++ b/third_party/node/update_npm_deps
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright 2017 The Chromium Authors
+# Copyright 2024 The Chromium Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
@@ -8,13 +8,48 @@
 #  1) Update package.json file to point to the desired version, or update the
 #     versions in download_npm_deps_manually.sh (for packages not pulled via
 #     `npm install`).
-#  2) Run this script.
-#  3) Upload the compressed node_modules.tar.gz file to the Google Storage
-#     bucket (commands to upload binaries are printed at step 2).
+#  2) Run this script without using any flag to download all the
+#     NPM dependencies locally.
+#  3) Upload the compressed node_modules.tar.gz file to the
+#     Google Cloud Storage and update the DEPS file by running this script with
+#     the `--upload` or `-u`, i.e. `update_npm_deps --upload`.
 #  4) Land a CL with the changes generated by this script.
 
 set -eu
 cd "$(dirname "$0")"
+
+upload=false  # Default value
+
+# The script can take a command line flag and check if it is valid.
+# If the flag `--upload` | `-u` is passed in, then the script
+# uploads the all the node_modules archive and updates the DEPS.
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    -u|--upload)
+      upload=true
+      shift
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
+done
+
+node_modules_file="node_modules.tar.gz"
+
+if [[ $upload = true ]]; then
+  if [[ ! -e ${node_modules_file} ]]; then
+    echo "Error: File '${node_modules_file}' does not exist."
+    echo "Please run ./update_npm_deps to download the all the NPM dependencies locally first."
+    echo "Exiting..."
+    exit 1
+  fi
+  ./upload_to_gcs_and_update_deps "${node_modules_file}"\
+      "src/third_party/node/node_modules"
+  echo "DONE uploading ${node_modules_file} and updating DEPS file.."
+  exit 0
+fi
 
 rm -rf node_modules
 
@@ -50,12 +85,22 @@ mv node_modules_filtered node_modules
 
 echo "After filtering:" size: $(du -h node_modules/ | tail -n1 | cut -f1) ", files: " $(find node_modules/ -type f | wc -l)
 
-tar cfz node_modules.tar.gz node_modules
-echo "After compressing:" size: $(du -h node_modules.tar.gz | tail -n1 | cut -f1)
+# Packs all contents under node_modules directory to node_modules.tar.gz without
+# using node_modules as the top level directory.
+# The directory to extract the archive is expected to be clear when using
+# GCS first class. So the archive needs to be downloaded to
+# `src/third_party/node/node_modules/` instead of `src/third_party/node/`.
+# The content will be extracted in the same directory.
+# By just packing only the contents, all the files will be under
+# `src/third_party/node/node_modules/`.
+# This aligns with the expected file structure of current dependencies.
+tar cfz "${node_modules_file}" -C node_modules .
+echo "After compressing:" size: $(du -h "${node_modules_file}" | tail -n1 | cut -f1)
 
+# Updating nod_modules.tar.gz.sha1.
 sha1="$(sha1sum node_modules.tar.gz | cut -d ' ' -f1)"
 echo "${sha1}" > node_modules.tar.gz.sha1
-echo "Please run the following manually to update Google Storage bucket:"
-echo "> gsutil.py cp node_modules.tar.gz gs://chromium-nodejs/${sha1}"
 echo "DONE"
 echo -e "---------------------------------------------------------"
+
+echo "Please run './update_npm_deps --upload' to upload the ${node_modules_file}"
