Migrate third_party/node/<platform> to GCS (Google Cloud Storage) first class deps.
This migrates the node/<platform> hooks to first class GCS dependencies.
See https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/docs/gcs_dependencies.md for more info.
The changes made in update_node_binaries will also update the DEPS
automatically.

A new mac_arm64/ directory is created.
This is a side effect of one of the requirements, which is that no paths
can clash. The filesystem that will use it is platform agnostic and will
need to support all artifacts for all the platforms. So if its
supporting mac and mac arm64, it needs both the node binaries for mac
and mac arm 64.

Bug: 337054714
Change-Id: Idfb62d1030da19a37d17cbd25e8ec18d239ca308
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5531695
Reviewed-by: Josip Sokcevic <sokcevic@chromium.org>
Commit-Queue: Clifford Cheng <cliffordcheng@chromium.org>
Reviewed-by: Demetrios Papadopoulos <dpapad@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1305276}

diff --git a/third_party/node/update_node_binaries b/third_party/node/update_node_binaries
--- a/third_party/node/update_node_binaries
+++ b/third_party/node/update_node_binaries
@@ -6,9 +6,11 @@
 
 # Script for updating Node binaries.
 # 1) Update NODE_VERSION variable below to the desired version.
-# 2) Run this script.
-# 3) Upload the binaries to the Google Storage bucket (commands to upload
-#    binaries are printed at step 2, look for "gsutil.py").
+# 2) Run this script without any flags first to download all the binaries
+#    locally.
+# 3) To upload the binaries to the Google Storage bucket, use the
+#    `--upload` or `-u` flag. This will upload the binaries to
+#    the Google Storage bucket and update the DEPS file.
 # 4) Land a CL with the changes generated by this script.
 
 set -eu
@@ -17,7 +19,120 @@ cd "$(dirname "$0")"
 BASE_URL="https://nodejs.org/dist"
 NODE_VERSION="v20.11.0"
 
-update_unix() {
+upload=false  # Default value
+
+# The script can take a command line flag and check if it is valid.
+# If the flag `--upload` | `-u` is passed in, then the script
+# uploads the binaries and update the DEPS.
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    -u|--upload)
+      upload=true
+      shift
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
+done
+
+# This function updates the DEPS file under `src/` using `gclient setdep`.
+# The current working directory is set to `src/third_party/node` at the top,
+# which is where the `update_node_binaries` located.
+# Therefore, the `--deps-file` need to be set to specify the DEPS file location.
+# Simply using a relative path, i.e. `../../DEPS`, would not work because
+# gclient runs from the src/ directory and it uses the `--deps-file` in some
+# processes. A relative path may result in a fatal message in those processes.
+set_deps() {
+  current_dir=$(dirname "$0" | pwd)
+  gclient setdep -r $1@$2 --deps-file="${current_dir}"/../../DEPS
+}
+
+# Helper function to upload content to GCS and set DEPS
+# 1) The Python script uploads content to Google Cloud Storage and returns a
+#    string that part of it contains the JSON which need be used to
+#    update the DEPS file. Here is a sample response.
+#Uploading mac/node-linux-x64.tar.gz as gs://chromium-nodejs/20.11.0/<sha1>
+#{
+#  "path": {
+#    "dep_type": "gcs",
+#    "bucket": "chromium-nodejs",
+#    "objects": [
+#      {
+#        "object_name":
+#          "20.11.0/f9a337cfa0e2b92d3e5c671c26b454bd8e99769e",
+#        "sha256sum":
+#          "0ba9cc91698c1f833a1fdc1fe0cb392d825ad484c71b0d84388ac80bfd3d6079",
+#        "size_bytes": 41024270,
+#        "generation": 1715983096515156
+#      }
+#    ]
+#  }
+#}
+# 2) grep gets only the JSON part in the string.
+# 3) jq extracts the `objects` in the returned JSON.
+# 4) sed generates the output by replacing newlines with commas and
+#    removing any trailing commas.
+# 5) The output will be like
+#    `${NODE_VERSION:1}/object_name,sha256sum,size_bytes,generation`
+# These values will be used to update the DEPS file.
+# first argument: google storage path
+# second argument: relative DEPS path
+upload_and_set() {
+  local sha1
+  local response
+  sha1="$(sha1sum $1 | cut -d ' ' -f1)"
+  response="$(upload_to_google_storage_first_class.py \
+      --bucket=chromium-nodejs \
+      --object-name=${NODE_VERSION:1}/${sha1} \
+      $1)"
+  set_deps $2 "$(echo ${response} | \
+    grep -o '{.*}' |
+    jq -r .path.objects[0][] |
+    sed -z 's/\n/,/g;s/,$/\n/')"
+}
+
+upload_unix(){
+  local SUFFIX="$1"
+  local FOLDER="$2"
+  local UPLOAD_FILE="${FOLDER}/node-${SUFFIX}.tar.gz"
+
+  if [[ -e "${UPLOAD_FILE}" ]]; then
+    if [[ "$SUFFIX" == "darwin-x64" ]]; then
+      local PATHNAME="src/third_party/node/mac"
+    fi
+
+    if [[ "$SUFFIX" == "darwin-arm64" ]]; then
+      local PATHNAME="src/third_party/node/mac_arm64"
+    fi
+
+    if [[ "$SUFFIX" == "linux-x64" ]]; then
+      local PATHNAME="src/third_party/node/linux"
+    fi
+    upload_and_set "${UPLOAD_FILE}" "${PATHNAME}"
+    echo "DONE uploading ${SUFFIX} binaries and updating DEPS file.."
+  else
+    echo "Error: File '${UPLOAD_FILE}' does not exist."
+    echo "Please run ./update_node_binaries to download binaries locally first."
+  fi
+}
+
+upload_win(){
+  local FILENAME="node.exe"
+  local FOLDER="win"
+  local UPLOAD_FILE="${FOLDER}/${FILENAME}"
+
+  if [[ -e "${UPLOAD_FILE}" ]]; then
+    upload_and_set "${UPLOAD_FILE}" src/third_party/node/win
+    echo "DONE uploading Windows binaries and updating DEPS file.."
+  else
+    echo "Error: File '$UPLOAD_FILE' does not exist."
+    echo "Please run ./update_node_binaries to download binaries locally first."
+  fi
+}
+
+download_unix() {
   local SUFFIX="$1"
   local FOLDER="$2"
   local FILENAME="node-${NODE_VERSION}-${SUFFIX}.tar.gz"
@@ -51,15 +166,9 @@ update_unix() {
   rm -rf "${FOLDER}/node-${SUFFIX}/"
   mv "${FOLDER}/node-${NODE_VERSION}-${SUFFIX}/" "${FOLDER}/node-${SUFFIX}/"
   tar cfz "${FOLDER}/node-${SUFFIX}.tar.gz" -C "${FOLDER}" "node-${SUFFIX}/"
-  local sha1
-  sha1="$(sha1sum ${FOLDER}/node-${SUFFIX}.tar.gz | cut -d ' ' -f1)"
-  echo "${sha1}" > "${FOLDER}/node-${SUFFIX}.tar.gz.sha1"
-  echo "Please execute manually the following:"
-  echo "> gsutil.py cp ${FOLDER}/node-${SUFFIX}.tar.gz gs://chromium-nodejs/${NODE_VERSION:1}/${sha1}"
-  echo "DONE updating for ${SUFFIX}."
 }
 
-update_win() {
+download_win() {
   local FILENAME="node.exe"
   local FOLDER="win"
   local WINDOWS_URL="${BASE_URL}/${NODE_VERSION}/win-x64/${FILENAME}"
@@ -76,23 +185,22 @@ update_win() {
     echo "SHA256 mismatch. Exiting..."
     exit 1
   fi
-
-  local sha1
-  sha1="$(sha1sum ${FOLDER}/node.exe | cut -d ' ' -f1)"
-  echo "${sha1}" > "${FOLDER}/node.exe.sha1"
-  echo "Please execute manually the following:"
-  echo "> gsutil.py cp ${FOLDER}/node.exe gs://chromium-nodejs/${NODE_VERSION:1}/${sha1}"
-  echo "DONE updating Windows."
 }
 
-# First download checksum file.
-rm -f "SHASUMS256.txt"
-wget "https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt"
 
-update_unix "darwin-x64" "mac"
-update_unix "darwin-arm64" "mac"
-update_unix "linux-x64" "linux"
-update_win
-
-# Update DEPS to point to the new Google Storage bucket subfolder.
-sed -i "s@\(chromium-nodejs/\)\([0-9\.]\)\+@\1${NODE_VERSION:1}@" ../../DEPS
+if [[ $upload != true ]]; then
+  # First download checksum file.
+  rm -f "SHASUMS256.txt"
+  wget "https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt"
+  download_unix "darwin-x64" "mac"
+  download_unix "darwin-arm64" "mac"
+  download_unix "linux-x64" "linux"
+  download_win
+  echo "To upload the binaries, please run ./update_node_binaries --upload"
+else
+  echo "Uploading to GCS and updating DEPS files..."
+  upload_unix "darwin-x64" "mac"
+  upload_unix "darwin-arm64" "mac"
+  upload_unix "linux-x64" "linux"
+  upload_win
+fi
